### PR TITLE
Add ability to send events via import vs track

### PR DESCRIPTION
**Pull request by williampratt**
This pr allows you to specify that events are sent via import instead of track. This allows you to set timestamps rather than the timestamp being the time the event was sent. I added tests. The exception test is failing even in the forked branch.

### CODE REVIEW

**Comment by williampratt** [comment]
Btw, I'm digging in to why the exception test is failing.

**Comment by williampratt** [comment]
This is working great for us in production. Can I get this merged in? The failing test fails on the current head branch as well. I haven't had time to look into it yet.

**Comment by hakobera** [comment]
@williampratt I fixed the exception test at #3. This error is caused mixpanel-ruby gem spec change.
Can you rebase or merge current master into this PR?

**Comment by williampratt** [comment]
@hakobera I merged. The tests all pass locally now, just waiting on Travis.

**Comment by hakobera** [comment]
@williampratt Thanks.

**Comment by hakobera** [comment]
@williampratt I release [fluent-plugin-mixpanel 0.0.6](https://rubygems.org/gems/fluent-plugin-mixpanel/versions/0.0.6) include this PR. Thanks for your contribution!

**Comment by williampratt** [comment]
@hakobera, ou are welcome. Let me know if I can help in the future.

**Pull request merged**
