### PR TITLE
Use handle tag name mixin

### PR DESCRIPTION
**Pull request by williampratt**
Use the HandleTagNameMixin provided by fluent rather than rolling our own. This doesn't break current behavior but adds the ability to add and remove suffixs and prefixs. I added tests for all.

### CODE REVIEW

**Comment by hakobera** [comment]
@williampratt Thanks. It's useful, but this is BREAKING CHANGE.
Merge this pull request, all `remove_tag_prefix` must be add suffix dot.

```
<match output.mixpanel.*>
  type mixpanel
  project_token YOUR_PROJECT_TOKEN
  distinct_id_key user_id
  remove_tag_prefix output.mixpanel <= This is not working, must be change to output.mixpanel.
  event_map_tag true
</match>
```

It my config design mistake.
Fluent::HandleTagNameMixin is official way to handle tag name, so it's OK to merge.
But wait a moment, I have to check our production settings before merge this.

**Comment by williampratt** [comment]
I don't think so. In your current implementation, you must supply the dot. With this config, you can supply the dot as well. We didn't supply the dot and all of our events started with a dot :(

**Comment by williampratt** [comment]
Hmmm, I wonder if we can work around this without it getting messy. I'm open to thoughts.

**Comment by williampratt** [comment]
My thought is to use a config option that appends a '.' if it doesn't exist. Set this to true by default but deprecated. Note it in the docs and on the next major release remove that option all together.

**Comment by williampratt** [comment]
Ok, I took a stab at it and added a test to ensure it works. Take a look and let me know what you think. If you are ok with it, I'll update the readme to note the new behavior and the deprecation of the old behavior in a future release. This is a win win as it will work either way, even if it's left at the default of true and they specify a '.'.

**Comment by hakobera** [comment]
@williampratt Thanks! Your work looks great! Please update README.

**Comment by williampratt** [comment]
I updated the readme. Let me know if you want me to change any of the wording.

**Comment by hakobera** [comment]
Thanks! :100:

**Comment by hakobera** [comment]
@williampratt I release [fluent-plugin-mixpanel 0.0.7](https://rubygems.org/gems/fluent-plugin-mixpanel).
I remove `use_legacy_prefix_behavior` when I release `0.1.0`, maybe next release.

**Pull request merged**
