### PR TITLE
Use time from record

### PR DESCRIPTION
**Pull request by williampratt**
Specifically for import, use the time from the record if it's specified

### CODE REVIEW

**Comment by hakobera** [comment]
I want you to write test about this change.

**Comment by williampratt** [comment]
Crap, I did, just didn't get checked in. I will check it in tomorrow when I get to work. We are using it now and it's working great both ways. The need is due to using import over track. Import allows you to set your own time and we have events that may be way in the past.

**Comment by williampratt** [comment]
Sorry for the delay, I've been busy. I added a test.

**Comment by williampratt** [comment]
Any chance we can merge this soon?

Thanks!

**Comment by hakobera** [comment]
@williampratt Thanks.

**Comment by hakobera** [comment]
@williampratt I released v0.0.8 included this change.

**Pull request merged**
